In [7]:
import numpy as np
x = np.zeros((6,6))
x

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
import numpy as np
x = np.array([10,20,30,40,50])
a=x*10
b= x+10
c = x/10
d = x-10
print(a,b,c,d)

[100 200 300 400 500] [20 30 40 50 60] [1. 2. 3. 4. 5.] [ 0 10 20 30 40]


In [29]:
import numpy as np
f=np.random.normal(1,100,(10,10))
g=np.reshape(f,(25,4))
f.flatten()

array([  66.7356863 , -151.71212078,   51.63044196, -109.13144636,
        199.66791197,  107.63836207, -146.66803024, -169.02823605,
         32.61239719,  165.43003879,   67.32153424, -236.46490141,
         -7.58750843,   51.28279406, -117.3280659 ,  117.82330741,
       -193.11466995,  -47.67246104,  -57.29007645,   56.65024232,
        -71.23134445, -101.40183154,  -96.30037715,    7.94685344,
        -72.16736172,   -7.26465338,  -21.07327544,  -93.81062327,
         11.72673752,   38.29713713,   25.69787591,  115.19421579,
       -148.22230737, -161.7376948 ,  244.07483352,    3.71327219,
        114.99010465,   -4.96313094,   75.93502944,  -69.56223002,
         56.73334485,  144.99566408,  152.38969892,   36.4691235 ,
       -201.85312711,  -97.89101329,   23.62172372,  131.97877544,
       -132.98245326,  120.75368356,  144.3484487 ,  -75.86198603,
        135.3405656 ,  -54.55146402,  139.89460831,  -72.97746002,
        -79.15521102,   78.3043828 ,   23.95009068,  -49.49934

In [53]:
import numpy as np
h = np.random.normal(1,100,(4,7))
np.asarray(h)[2,:]=7
h

array([[ 133.99057269,  156.37445256, -168.0096566 ,   46.23791143,
         -51.73619659,   75.06806506,   65.25897284],
       [-240.48089133, -148.0091203 ,   62.00647635,  248.23604118,
          -0.71386251,  -28.50223912, -109.41918432],
       [   7.        ,    7.        ,    7.        ,    7.        ,
           7.        ,    7.        ,    7.        ],
       [  95.31618579,  -63.60199732,  -77.02470215,   29.1812328 ,
         -67.30258059,  -98.39616182,   39.00298991]])

In [60]:
import numpy as np
k = [(1,4,7,8,5),
    (6,4,9,8,5)]
p = [(9,7,1,2,3),
    (6,3,9,5,4),
    (8,7,5,6,4),
    (7,1,2,3,3)]
c=np.transpose(p)
np.matmul(k,c)

array([[ 75, 141, 139,  64],
       [122, 189, 189, 103]])